### ISSUE TITLE
Missing LICENSE file in release tarball.

### ISSUE THREAD

**Issue by ericsnowcurrently** [foliojs/unicode-properties#10]
I found your `LICENSE` file at top of the repo.  However, there is no `LICENSE` file in the release tarball (under https://registry.npmjs.org/).  There should be.

**Comment by liborm85** [comment]
You probably don't use latest version, there is everything available.

**Comment by ericsnowcurrently** [comment]
Yep, we're pinned at 1.1.0. :/
